//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagementClient.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/ShopManagement")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductPriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductPrice {
            get {
                return this.ProductPriceField;
            }
            set {
                if ((this.ProductPriceField.Equals(value) != true)) {
                    this.ProductPriceField = value;
                    this.RaisePropertyChanged("ProductPrice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bill", Namespace="http://schemas.datacontract.org/2004/07/ShopManagement")]
    [System.SerializableAttribute()]
    public partial class Bill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                if ((this.dateField.Equals(value) != true)) {
                    this.dateField = value;
                    this.RaisePropertyChanged("date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductService.Iproducts")]
    public interface Iproducts {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iproducts/AddProduct", ReplyAction="http://tempuri.org/Iproducts/AddProductResponse")]
        string AddProduct(ShopManagementClient.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iproducts/AddProduct", ReplyAction="http://tempuri.org/Iproducts/AddProductResponse")]
        System.Threading.Tasks.Task<string> AddProductAsync(ShopManagementClient.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iproducts/UpdateProductDetails", ReplyAction="http://tempuri.org/Iproducts/UpdateProductDetailsResponse")]
        void UpdateProductDetails(ShopManagementClient.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iproducts/UpdateProductDetails", ReplyAction="http://tempuri.org/Iproducts/UpdateProductDetailsResponse")]
        System.Threading.Tasks.Task UpdateProductDetailsAsync(ShopManagementClient.ProductService.Product product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iproducts/GetProduct", ReplyAction="http://tempuri.org/Iproducts/GetProductResponse")]
        ShopManagementClient.ProductService.Product GetProduct(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iproducts/GetProduct", ReplyAction="http://tempuri.org/Iproducts/GetProductResponse")]
        System.Threading.Tasks.Task<ShopManagementClient.ProductService.Product> GetProductAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iproducts/StoreBill", ReplyAction="http://tempuri.org/Iproducts/StoreBillResponse")]
        int StoreBill(ShopManagementClient.ProductService.Bill b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iproducts/StoreBill", ReplyAction="http://tempuri.org/Iproducts/StoreBillResponse")]
        System.Threading.Tasks.Task<int> StoreBillAsync(ShopManagementClient.ProductService.Bill b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iproducts/GetProductPrice", ReplyAction="http://tempuri.org/Iproducts/GetProductPriceResponse")]
        int GetProductPrice(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Iproducts/GetProductPrice", ReplyAction="http://tempuri.org/Iproducts/GetProductPriceResponse")]
        System.Threading.Tasks.Task<int> GetProductPriceAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IproductsChannel : ShopManagementClient.ProductService.Iproducts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IproductsClient : System.ServiceModel.ClientBase<ShopManagementClient.ProductService.Iproducts>, ShopManagementClient.ProductService.Iproducts {
        
        public IproductsClient() {
        }
        
        public IproductsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IproductsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IproductsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IproductsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AddProduct(ShopManagementClient.ProductService.Product product) {
            return base.Channel.AddProduct(product);
        }
        
        public System.Threading.Tasks.Task<string> AddProductAsync(ShopManagementClient.ProductService.Product product) {
            return base.Channel.AddProductAsync(product);
        }
        
        public void UpdateProductDetails(ShopManagementClient.ProductService.Product product) {
            base.Channel.UpdateProductDetails(product);
        }
        
        public System.Threading.Tasks.Task UpdateProductDetailsAsync(ShopManagementClient.ProductService.Product product) {
            return base.Channel.UpdateProductDetailsAsync(product);
        }
        
        public ShopManagementClient.ProductService.Product GetProduct(int id) {
            return base.Channel.GetProduct(id);
        }
        
        public System.Threading.Tasks.Task<ShopManagementClient.ProductService.Product> GetProductAsync(int id) {
            return base.Channel.GetProductAsync(id);
        }
        
        public int StoreBill(ShopManagementClient.ProductService.Bill b) {
            return base.Channel.StoreBill(b);
        }
        
        public System.Threading.Tasks.Task<int> StoreBillAsync(ShopManagementClient.ProductService.Bill b) {
            return base.Channel.StoreBillAsync(b);
        }
        
        public int GetProductPrice(int id) {
            return base.Channel.GetProductPrice(id);
        }
        
        public System.Threading.Tasks.Task<int> GetProductPriceAsync(int id) {
            return base.Channel.GetProductPriceAsync(id);
        }
    }
}
